### PR TITLE
Rename mnist_openfl to mnist_fl

### PR DESCRIPTION
**Pull request by danieljanes**
# Summary

This PR renames the MLCube example `mnist_openfl` to `mnist_fl`.

# Background

As discussed previously with @msheller and others, the intent of this code example is to show how MLCube can be used with different FL frameworks. We are working towards providing MLCube support in Flower (https://flower.dev, PR: https://github.com/adap/flower/pull/779), but we received feedback from early adopters who were confused by the naming when we pointed them at the `mlcube_examples` repo. The renaming will hopefully help users to understand that the approach presented is framework-agnostic.

Being a first-time contributor to MLCube, is there anything else I should update?

### CODE REVIEW

**Comment by danieljanes** [comment]
Given that #33 is already merged, I've also updated the setup instruction in `mnist_fl/pytorch/README.md` and `mnist_fl/tensorflow/README.md`.

**Comment by msheller** [comment]
+1 to this.

At some point, it would be good for us to formalize this mlcube interface somehow, rather than having to point folks to a particular example mlcube.

**Comment by danieljanes** [comment]
> At some point, it would be good for us to formalize this mlcube interface somehow, rather than having to point folks to a particular example mlcube.

Fully agree. Where should this spec live? My first guess would be the MLCube repo/docs, but there might be a better place for it. I've created an issue to follow up on this: https://github.com/mlcommons/mlcube/issues/222

**Comment by danieljanes** [comment]
@sergey-serebryakov @davidjurado friendly ping (since you're the two most recent contributors here), is there anything I can do to help move this forward?

**Review by bitfort — APPROVED** [review]
Thanks!

**Pull request merged**
